# Generated by Django 5.2.5 on 2025-10-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('cafe', 'Café'), ('insumos', 'Insumos'), ('equipamiento', 'Equipamiento'), ('desechables', 'Desechables'), ('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('otros', 'Otros')], max_length=20)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('gramo', 'Gramo'), ('mililitro', 'Mililitro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('bolsa', 'Bolsa')], max_length=20)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('en_pedido', 'En pedido'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20)),
                ('requiere_alerta', models.BooleanField(default=False)),
                ('imagen_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
    ]
