# Generated by Django 5.2.5 on 2025-11-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_column='codigo_producto', max_length=50, unique=True)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('categoria', models.CharField(choices=[('cafe', 'Café'), ('insumos', 'Insumos'), ('equipamiento', 'Equipamiento'), ('desechables', 'Desechables'), ('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('otros', 'Otros')], db_column='categoria', max_length=20)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('gramo', 'Gramo'), ('mililitro', 'Mililitro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('bolsa', 'Bolsa')], db_column='unidad_medida', max_length=20)),
                ('cantidad_actual', models.IntegerField(db_column='cantidad_actual', default=0)),
                ('cantidad_minima', models.IntegerField(db_column='cantidad_minima')),
                ('cantidad_maxima', models.IntegerField(blank=True, db_column='cantidad_maxima', null=True)),
                ('precio_unitario', models.IntegerField(blank=True, db_column='precio_unitario', null=True)),
                ('precio_venta', models.IntegerField(blank=True, db_column='precio_venta', null=True)),
                ('codigo_qr', models.CharField(blank=True, db_column='codigo_qr', max_length=255, null=True)),
                ('codigo_barra', models.CharField(blank=True, db_column='codigo_barra', max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, db_column='proveedor', max_length=100, null=True)),
                ('contacto_proveedor', models.CharField(blank=True, db_column='contacto_proveedor', max_length=100, null=True)),
                ('fecha_ultimo_ingreso', models.DateTimeField(blank=True, db_column='fecha_ultimo_ingreso', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fecha_vencimiento', null=True)),
                ('lote', models.CharField(blank=True, db_column='lote', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('en_pedido', 'En pedido'), ('descontinuado', 'Descontinuado')], db_column='estado', default='disponible', max_length=20)),
                ('requiere_alerta', models.BooleanField(db_column='requiere_alerta', default=False)),
                ('imagen_producto', models.CharField(blank=True, db_column='imagen_producto', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_actualizados', to='empleado.empleado')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_creados', to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='AlertasInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_critico', 'Stock Crítico'), ('producto_vencido', 'Producto Vencido'), ('por_vencer', 'Por Vencer'), ('sin_stock', 'Sin Stock'), ('sobre_stock', 'Sobre Stock')], db_column='tipo_alerta', max_length=20)),
                ('mensaje', models.TextField(db_column='mensaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], db_column='estado', default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], db_column='prioridad', default='media', max_length=20)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True, db_column='fecha_alerta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, db_column='fecha_resolucion', null=True)),
                ('notas_resolucion', models.TextField(blank=True, db_column='notas_resolucion', null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, db_column='resuelto_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to='empleado.empleado')),
                ('inventario_id', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.inventario')),
            ],
            options={
                'db_table': 'alertas_inventario',
                'indexes': [models.Index(fields=['inventario_id'], name='alertas_inv_inventa_ddb761_idx'), models.Index(fields=['estado'], name='alertas_inv_estado_f79eed_idx'), models.Index(fields=['tipo_alerta'], name='alertas_inv_tipo_al_d1e97c_idx'), models.Index(fields=['prioridad'], name='alertas_inv_priorid_5600a2_idx'), models.Index(fields=['fecha_alerta'], name='alertas_inv_fecha_a_6f72e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolución'), ('transferencia', 'Transferencia'), ('venta', 'Venta')], db_column='tipo_movimiento', max_length=20)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('cantidad_anterior', models.IntegerField(db_column='cantidad_anterior')),
                ('cantidad_nueva', models.IntegerField(db_column='cantidad_nueva')),
                ('precio_unitario', models.IntegerField(blank=True, db_column='precio_unitario', null=True)),
                ('costo_total', models.IntegerField(blank=True, db_column='costo_total', null=True)),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=255, null=True)),
                ('documento_referencia', models.CharField(blank=True, db_column='documento_referencia', max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, db_column='proveedor', max_length=100, null=True)),
                ('ubicacion_origen', models.CharField(blank=True, db_column='ubicacion_origen', max_length=100, null=True)),
                ('ubicacion_destino', models.CharField(blank=True, db_column='ubicacion_destino', max_length=100, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='fecha_movimiento')),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('empleado_id', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='empleado.empleado')),
                ('inventario_id', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario')),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'indexes': [models.Index(fields=['inventario_id'], name='movimientos_inventa_15b05d_idx'), models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_a03876_idx'), models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_c279a0_idx'), models.Index(fields=['empleado_id'], name='movimientos_emplead_bf4c21_idx'), models.Index(fields=['inventario_id', 'fecha_movimiento', 'tipo_movimiento'], name='movimientos_inventa_44e014_idx')],
            },
        ),
    ]
