# Generated by Django 5.2.5 on 2025-11-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_column='codigo_producto', max_length=50, unique=True)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('categoria', models.CharField(choices=[('cafe', 'Café'), ('insumos', 'Insumos'), ('equipamiento', 'Equipamiento'), ('desechables', 'Desechables'), ('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('otros', 'Otros')], db_column='categoria', max_length=20)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('gramo', 'Gramo'), ('mililitro', 'Mililitro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('bolsa', 'Bolsa')], db_column='unidad_medida', max_length=20)),
                ('cantidad_actual', models.DecimalField(db_column='cantidad_actual', decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_minima', models.DecimalField(db_column='cantidad_minima', decimal_places=2, max_digits=10)),
                ('cantidad_maxima', models.DecimalField(blank=True, db_column='cantidad_maxima', decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='precio_unitario', decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, db_column='precio_venta', decimal_places=2, max_digits=10, null=True)),
                ('codigo_qr', models.CharField(blank=True, db_column='codigo_qr', max_length=255, null=True)),
                ('codigo_barra', models.CharField(blank=True, db_column='codigo_barra', max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, db_column='proveedor', max_length=100, null=True)),
                ('contacto_proveedor', models.CharField(blank=True, db_column='contacto_proveedor', max_length=100, null=True)),
                ('fecha_ultimo_ingreso', models.DateTimeField(blank=True, db_column='fecha_ultimo_ingreso', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fecha_vencimiento', null=True)),
                ('lote', models.CharField(blank=True, db_column='lote', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('en_pedido', 'En pedido'), ('descontinuado', 'Descontinuado')], db_column='estado', default='disponible', max_length=20)),
                ('requiere_alerta', models.BooleanField(db_column='requiere_alerta', default=False)),
                ('imagen_producto', models.CharField(blank=True, db_column='imagen_producto', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_actualizados', to='empleado.empleado')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_creados', to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
    ]
