# Generated by Django 5.2.5 on 2025-12-22 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='alertasinventario',
            name='inventario_id',
            field=models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.inventario'),
        ),
        migrations.AddField(
            model_name='movimientosinventario',
            name='empleado_id',
            field=models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='empleado.empleado'),
        ),
        migrations.AddField(
            model_name='movimientosinventario',
            name='inventario_id',
            field=models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['proveedor'], name='inventario_proveed_69029b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasinventario',
            index=models.Index(fields=['inventario_id'], name='alertas_inv_inventa_ddb761_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasinventario',
            index=models.Index(fields=['estado'], name='alertas_inv_estado_f79eed_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasinventario',
            index=models.Index(fields=['tipo_alerta'], name='alertas_inv_tipo_al_d1e97c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasinventario',
            index=models.Index(fields=['prioridad'], name='alertas_inv_priorid_5600a2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasinventario',
            index=models.Index(fields=['fecha_alerta'], name='alertas_inv_fecha_a_6f72e1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['inventario_id'], name='movimientos_inventa_15b05d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_a03876_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_c279a0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['empleado_id'], name='movimientos_emplead_bf4c21_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['inventario_id', 'fecha_movimiento', 'tipo_movimiento'], name='movimientos_inventa_44e014_idx'),
        ),
    ]
