# Generated by Django 5.2.5 on 2025-12-18 06:34

import django.db.models.deletion
from django.db import migrations, models, connection


def migrate_proveedor_data_forward(apps, schema_editor):
    """
    Migrar datos de proveedor de texto (nombre) a ForeignKey (ID)
    """
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    
    # Crear un diccionario de nombres de proveedores a IDs
    proveedor_map = {}
    for proveedor in Proveedor.objects.all():
        proveedor_map[proveedor.nombre] = proveedor.id
    
    # Usar raw SQL para migrar los datos
    with connection.cursor() as cursor:
        # Paso 1: Agregar una columna temporal para el ID del proveedor
        try:
            cursor.execute("ALTER TABLE inventario ADD COLUMN proveedor_id_temp INT NULL")
        except Exception:
            # Si la columna ya existe, continuar
            pass
        
        # Paso 2: Migrar datos: actualizar proveedor_id_temp con IDs basados en nombres
        cursor.execute("""
            UPDATE inventario i
            INNER JOIN proveedores p ON i.proveedor = p.nombre
            SET i.proveedor_id_temp = p.id
            WHERE i.proveedor IS NOT NULL AND i.proveedor != ''
        """)
        
        # Paso 3: Eliminar la columna antigua de texto
        try:
            cursor.execute("ALTER TABLE inventario DROP COLUMN proveedor")
        except Exception:
            pass
        
        # Paso 4: Renombrar la columna temporal a proveedor_id
        try:
            cursor.execute("ALTER TABLE inventario CHANGE COLUMN proveedor_id_temp proveedor_id INT NULL")
        except Exception:
            # Si no existe proveedor_id_temp, la columna ya fue renombrada
            pass


def migrate_proveedor_data_reverse(apps, schema_editor):
    """
    Revertir migración: convertir IDs de proveedores a nombres
    """
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    
    with connection.cursor() as cursor:
        # Agregar columna VARCHAR para nombres
        try:
            cursor.execute("ALTER TABLE inventario ADD COLUMN proveedor VARCHAR(100) NULL")
        except Exception:
            pass
        
        # Migrar IDs a nombres
        cursor.execute("""
            UPDATE inventario i
            INNER JOIN proveedores p ON i.proveedor_id = p.id
            SET i.proveedor = p.nombre
            WHERE i.proveedor_id IS NOT NULL
        """)
        
        # Eliminar columna de ID
        try:
            cursor.execute("ALTER TABLE inventario DROP COLUMN proveedor_id")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        # Migrar los datos usando raw SQL
        migrations.RunPython(migrate_proveedor_data_forward, migrate_proveedor_data_reverse),
        
        # Actualizar el estado de Django para reflejar el cambio en el modelo
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Las operaciones de base de datos ya se hicieron en RunPython
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='inventario',
                    name='proveedor',
                    field=models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor'),
                ),
                migrations.AddIndex(
                    model_name='inventario',
                    index=models.Index(fields=['proveedor'], name='inventario_proveed_69029b_idx'),
                ),
            ]
        ),
    ]
