# Generated by Django 5.2.5 on 2025-12-22 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_column='clave', max_length=100, unique=True)),
                ('valor', models.TextField(db_column='valor')),
                ('tipo', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], db_column='tipo', default='string', max_length=20)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'configuracion_app',
                'indexes': [models.Index(fields=['categoria'], name='configuraci_categor_23e376_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogsActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_column='modulo', max_length=50)),
                ('accion', models.CharField(db_column='accion', max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, db_column='tabla_afectada', max_length=100, null=True)),
                ('registro_id', models.IntegerField(blank=True, db_column='registro_id', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('datos_anteriores', models.JSONField(blank=True, db_column='datos_anteriores', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, db_column='datos_nuevos', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user_agent', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('empleado_id', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actividad', to='empleado.empleado')),
            ],
            options={
                'db_table': 'logs_actividad',
                'indexes': [models.Index(fields=['empleado_id'], name='logs_activi_emplead_15c2ad_idx'), models.Index(fields=['modulo'], name='logs_activi_modulo_88cde2_idx'), models.Index(fields=['fecha_registro'], name='logs_activi_fecha_r_74ca61_idx'), models.Index(fields=['tabla_afectada', 'registro_id'], name='logs_activi_tabla_a_100214_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(db_column='nombre_reporte', max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('asistencia', 'Asistencia'), ('inventario', 'Inventario'), ('personal', 'Personal'), ('financiero', 'Financiero'), ('personalizado', 'Personalizado')], db_column='tipo_reporte', max_length=20)),
                ('periodo_inicio', models.DateField(blank=True, db_column='periodo_inicio', null=True)),
                ('periodo_fin', models.DateField(blank=True, db_column='periodo_fin', null=True)),
                ('parametros', models.JSONField(blank=True, db_column='parametros', null=True)),
                ('archivo_generado', models.CharField(blank=True, db_column='archivo_generado', max_length=255, null=True)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], db_column='formato', default='pdf', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fecha_generacion')),
                ('tiempo_generacion', models.IntegerField(blank=True, db_column='tiempo_generacion', null=True)),
                ('generado_por', models.ForeignKey(blank=True, db_column='generado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to='empleado.empleado')),
            ],
            options={
                'db_table': 'reportes',
                'indexes': [models.Index(fields=['tipo_reporte'], name='reportes_tipo_re_d41df6_idx'), models.Index(fields=['fecha_generacion'], name='reportes_fecha_g_36337f_idx'), models.Index(fields=['generado_por'], name='reportes_generad_a34ad9_idx')],
            },
        ),
    ]
