"""
Comando de Django para cargar los datos de inventario desde el archivo SQL.
"""
from django.core.management.base import BaseCommand
from inventario.models import Inventario
from django.utils import timezone
from datetime import datetime


class Command(BaseCommand):
    help = 'Carga los datos de inventario desde el archivo SQL'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Iniciando carga de datos de inventario...'))
        
        # Datos de inventario
        productos = [
            {
                'codigo_producto': 'CAFE-001',
                'nombre_producto': 'Marley Coffee - One Love Organic',
                'descripcion': 'Café orgánico en grano 340g, tueste medio',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 50.00,
                'cantidad_minima': 15.00,
                'cantidad_maxima': 100.00,
                'precio_unitario': 8500.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-CAFE-001',
                'codigo_barra': '7000000000001',
                'ubicacion': 'Bodega A1',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-002',
                'nombre_producto': 'Marley Coffee - Smile Jamaica',
                'descripcion': 'Café Jamaica Blue Mountain en grano 340g',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 30.00,
                'cantidad_minima': 10.00,
                'cantidad_maxima': 80.00,
                'precio_unitario': 9200.00,
                'precio_venta': 13990.00,
                'codigo_qr': 'QR-CAFE-002',
                'codigo_barra': '7000000000002',
                'ubicacion': 'Bodega A1',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-003',
                'nombre_producto': 'Marley Coffee - Buffalo Soldier',
                'descripcion': 'Café oscuro intenso en grano 340g',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 45.00,
                'cantidad_minima': 12.00,
                'cantidad_maxima': 90.00,
                'precio_unitario': 8800.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-CAFE-003',
                'codigo_barra': '7000000000003',
                'ubicacion': 'Bodega A1',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-004',
                'nombre_producto': 'Marley Coffee - Lively Up',
                'descripcion': 'Café espresso en grano 340g',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 40.00,
                'cantidad_minima': 15.00,
                'cantidad_maxima': 100.00,
                'precio_unitario': 8600.00,
                'precio_venta': 12790.00,
                'codigo_qr': 'QR-CAFE-004',
                'codigo_barra': '7000000000004',
                'ubicacion': 'Bodega A1',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-005',
                'nombre_producto': 'Marley Coffee - Mystic Morning',
                'descripcion': 'Café suave descafeinado en grano 340g',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 25.00,
                'cantidad_minima': 8.00,
                'cantidad_maxima': 60.00,
                'precio_unitario': 9500.00,
                'precio_venta': 14490.00,
                'codigo_qr': 'QR-CAFE-005',
                'codigo_barra': '7000000000005',
                'ubicacion': 'Bodega A1',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-011',
                'nombre_producto': 'Marley Coffee - One Love Molido',
                'descripcion': 'Café orgánico molido 340g, tueste medio',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 60.00,
                'cantidad_minima': 20.00,
                'cantidad_maxima': 120.00,
                'precio_unitario': 8200.00,
                'precio_venta': 12490.00,
                'codigo_qr': 'QR-CAFE-011',
                'codigo_barra': '7000000000006',
                'ubicacion': 'Bodega A2',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-012',
                'nombre_producto': 'Marley Coffee - Get Up Stand Up',
                'descripcion': 'Café molido tueste oscuro 340g',
                'categoria': 'cafe',
                'unidad_medida': 'paquete',
                'cantidad_actual': 55.00,
                'cantidad_minima': 18.00,
                'cantidad_maxima': 110.00,
                'precio_unitario': 8400.00,
                'precio_venta': 12690.00,
                'codigo_qr': 'QR-CAFE-012',
                'codigo_barra': '7000000000007',
                'ubicacion': 'Bodega A2',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-021',
                'nombre_producto': 'Marley Coffee - Cápsulas One Love',
                'descripcion': 'Cápsulas compatibles Nespresso 10 unid.',
                'categoria': 'cafe',
                'unidad_medida': 'caja',
                'cantidad_actual': 80.00,
                'cantidad_minima': 25.00,
                'cantidad_maxima': 150.00,
                'precio_unitario': 4200.00,
                'precio_venta': 6990.00,
                'codigo_qr': 'QR-CAFE-021',
                'codigo_barra': '7000000000008',
                'ubicacion': 'Bodega A3',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'CAFE-022',
                'nombre_producto': 'Marley Coffee - Cápsulas Lively Up',
                'descripcion': 'Cápsulas compatibles Nespresso 10 unid.',
                'categoria': 'cafe',
                'unidad_medida': 'caja',
                'cantidad_actual': 75.00,
                'cantidad_minima': 25.00,
                'cantidad_maxima': 150.00,
                'precio_unitario': 4200.00,
                'precio_venta': 6990.00,
                'codigo_qr': 'QR-CAFE-022',
                'codigo_barra': '7000000000009',
                'ubicacion': 'Bodega A3',
                'proveedor': 'Distribuidora Marley Chile',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-101',
                'nombre_producto': 'Taza Marley Coffee Logo',
                'descripcion': 'Taza cerámica 350ml con logo Marley',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 100.00,
                'cantidad_minima': 20.00,
                'cantidad_maxima': 200.00,
                'precio_unitario': 3500.00,
                'precio_venta': 7990.00,
                'codigo_qr': 'QR-MERCH-101',
                'codigo_barra': '7000000000010',
                'ubicacion': 'Vitrina Principal',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-102',
                'nombre_producto': 'Taza One Love Edición Especial',
                'descripcion': 'Taza cerámica premium 400ml',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 50.00,
                'cantidad_minima': 15.00,
                'cantidad_maxima': 100.00,
                'precio_unitario': 4200.00,
                'precio_venta': 9990.00,
                'codigo_qr': 'QR-MERCH-102',
                'codigo_barra': '7000000000011',
                'ubicacion': 'Vitrina Principal',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-103',
                'nombre_producto': 'Mug Térmico Marley',
                'descripcion': 'Vaso térmico acero inoxidable 500ml',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 40.00,
                'cantidad_minima': 10.00,
                'cantidad_maxima': 80.00,
                'precio_unitario': 6500.00,
                'precio_venta': 14990.00,
                'codigo_qr': 'QR-MERCH-103',
                'codigo_barra': '7000000000012',
                'ubicacion': 'Vitrina Principal',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-201',
                'nombre_producto': 'Polera Marley Coffee - Talla S',
                'descripcion': 'Polera algodón 100% con estampado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 30.00,
                'cantidad_minima': 8.00,
                'cantidad_maxima': 60.00,
                'precio_unitario': 5500.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-MERCH-201',
                'codigo_barra': '7000000000013',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-202',
                'nombre_producto': 'Polera Marley Coffee - Talla M',
                'descripcion': 'Polera algodón 100% con estampado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 40.00,
                'cantidad_minima': 10.00,
                'cantidad_maxima': 80.00,
                'precio_unitario': 5500.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-MERCH-202',
                'codigo_barra': '7000000000014',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-203',
                'nombre_producto': 'Polera Marley Coffee - Talla L',
                'descripcion': 'Polera algodón 100% con estampado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 35.00,
                'cantidad_minima': 10.00,
                'cantidad_maxima': 70.00,
                'precio_unitario': 5500.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-MERCH-203',
                'codigo_barra': '7000000000015',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-204',
                'nombre_producto': 'Polera Marley Coffee - Talla XL',
                'descripcion': 'Polera algodón 100% con estampado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 25.00,
                'cantidad_minima': 8.00,
                'cantidad_maxima': 50.00,
                'precio_unitario': 5500.00,
                'precio_venta': 12990.00,
                'codigo_qr': 'QR-MERCH-204',
                'codigo_barra': '7000000000016',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-205',
                'nombre_producto': 'Gorro Marley Coffee',
                'descripcion': 'Gorro tejido con logo bordado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 45.00,
                'cantidad_minima': 12.00,
                'cantidad_maxima': 90.00,
                'precio_unitario': 4200.00,
                'precio_venta': 9990.00,
                'codigo_qr': 'QR-MERCH-205',
                'codigo_barra': '7000000000017',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-206',
                'nombre_producto': 'Delantal Barista Marley',
                'descripcion': 'Delantal jean con bolsillos',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 20.00,
                'cantidad_minima': 5.00,
                'cantidad_maxima': 40.00,
                'precio_unitario': 7800.00,
                'precio_venta': 16990.00,
                'codigo_qr': 'QR-MERCH-206',
                'codigo_barra': '7000000000018',
                'ubicacion': 'Bodega Merchandising',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-301',
                'nombre_producto': 'Llavero Marley Coffee',
                'descripcion': 'Llavero metal con logo grabado',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 150.00,
                'cantidad_minima': 30.00,
                'cantidad_maxima': 300.00,
                'precio_unitario': 800.00,
                'precio_venta': 2990.00,
                'codigo_qr': 'QR-MERCH-301',
                'codigo_barra': '7000000000019',
                'ubicacion': 'Mostrador',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-302',
                'nombre_producto': 'Botella Reutilizable Marley',
                'descripcion': 'Botella plástico libre BPA 750ml',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 60.00,
                'cantidad_minima': 15.00,
                'cantidad_maxima': 120.00,
                'precio_unitario': 3200.00,
                'precio_venta': 7990.00,
                'codigo_qr': 'QR-MERCH-302',
                'codigo_barra': '7000000000020',
                'ubicacion': 'Vitrina Principal',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-303',
                'nombre_producto': 'Bolsa Tote Marley Coffee',
                'descripcion': 'Bolsa tela ecológica reutilizable',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 80.00,
                'cantidad_minima': 20.00,
                'cantidad_maxima': 150.00,
                'precio_unitario': 2500.00,
                'precio_venta': 5990.00,
                'codigo_qr': 'QR-MERCH-303',
                'codigo_barra': '7000000000021',
                'ubicacion': 'Mostrador',
                'proveedor': 'Textil Express',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-304',
                'nombre_producto': 'Sticker Pack Marley',
                'descripcion': 'Pack 5 stickers adhesivos variados',
                'categoria': 'otros',
                'unidad_medida': 'paquete',
                'cantidad_actual': 200.00,
                'cantidad_minima': 50.00,
                'cantidad_maxima': 400.00,
                'precio_unitario': 500.00,
                'precio_venta': 1990.00,
                'codigo_qr': 'QR-MERCH-304',
                'codigo_barra': '7000000000022',
                'ubicacion': 'Mostrador',
                'proveedor': 'Imprenta Digital',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-305',
                'nombre_producto': 'Imán Refrigerador Marley',
                'descripcion': 'Imán decorativo con diseños Marley',
                'categoria': 'otros',
                'unidad_medida': 'unidad',
                'cantidad_actual': 120.00,
                'cantidad_minima': 30.00,
                'cantidad_maxima': 250.00,
                'precio_unitario': 600.00,
                'precio_venta': 1990.00,
                'codigo_qr': 'QR-MERCH-305',
                'codigo_barra': '7000000000023',
                'ubicacion': 'Mostrador',
                'proveedor': 'Imprenta Digital',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-401',
                'nombre_producto': 'Prensa Francesa Marley 1L',
                'descripcion': 'Cafetera prensa francesa vidrio',
                'categoria': 'equipamiento',
                'unidad_medida': 'unidad',
                'cantidad_actual': 15.00,
                'cantidad_minima': 5.00,
                'cantidad_maxima': 30.00,
                'precio_unitario': 12000.00,
                'precio_venta': 24990.00,
                'codigo_qr': 'QR-MERCH-401',
                'codigo_barra': '7000000000024',
                'ubicacion': 'Vitrina Premium',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-402',
                'nombre_producto': 'Molinillo Manual Marley',
                'descripcion': 'Molinillo café manual cerámica',
                'categoria': 'equipamiento',
                'unidad_medida': 'unidad',
                'cantidad_actual': 12.00,
                'cantidad_minima': 4.00,
                'cantidad_maxima': 25.00,
                'precio_unitario': 18000.00,
                'precio_venta': 34990.00,
                'codigo_qr': 'QR-MERCH-402',
                'codigo_barra': '7000000000025',
                'ubicacion': 'Vitrina Premium',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
            {
                'codigo_producto': 'MERCH-403',
                'nombre_producto': 'Set Barista Marley',
                'descripcion': 'Kit completo: tamper, jarra, cuchara',
                'categoria': 'equipamiento',
                'unidad_medida': 'unidad',
                'cantidad_actual': 10.00,
                'cantidad_minima': 3.00,
                'cantidad_maxima': 20.00,
                'precio_unitario': 22000.00,
                'precio_venta': 44990.00,
                'codigo_qr': 'QR-MERCH-403',
                'codigo_barra': '7000000000026',
                'ubicacion': 'Vitrina Premium',
                'proveedor': 'Importadora Nacional',
                'estado': 'disponible',
                'requiere_alerta': False,
                'activo': True,
            },
        ]
        
        creados = 0
        actualizados = 0
        
        for producto_data in productos:
            producto, created = Inventario.objects.update_or_create(
                codigo_producto=producto_data['codigo_producto'],
                defaults=producto_data
            )
            if created:
                creados += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✓ Creado: {producto.nombre_producto}')
                )
            else:
                actualizados += 1
                self.stdout.write(
                    self.style.WARNING(f'↻ Actualizado: {producto.nombre_producto}')
                )
        
        self.stdout.write(self.style.SUCCESS(
            f'\n✅ Proceso completado: {creados} productos creados, {actualizados} actualizados'
        ))

