# Generated by Django 5.2.5 on 2025-11-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_column='rut', max_length=12, unique=True)),
                ('nombre', models.CharField(db_column='nombres', max_length=100)),
                ('apellido', models.CharField(db_column='apellidos', max_length=100)),
                ('correo', models.EmailField(blank=True, db_column='email', max_length=100, null=True)),
                ('celular', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('direccion', models.TextField(blank=True, db_column='direccion', null=True)),
                ('rol', models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('empleado', 'Empleado')], db_column='rol', default='empleado', max_length=20, null=True)),
                ('cargo', models.CharField(db_column='cargo', max_length=100)),
                ('departamento', models.CharField(blank=True, db_column='departamento', max_length=100, null=True)),
                ('fecha_contratacion', models.DateField(db_column='fecha_contratacion')),
                ('fecha_termino', models.DateField(blank=True, db_column='fecha_termino', null=True)),
                ('salario', models.IntegerField(blank=True, db_column='salario', null=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], db_column='tipo_contrato', default='indefinido', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('desvinculado', 'Desvinculado')], db_column='estado', default='activo', max_length=20)),
                ('password', models.CharField(blank=True, db_column='password', max_length=255, null=True)),
                ('foto_perfil', models.CharField(blank=True, db_column='foto_perfil', max_length=255, null=True)),
                ('huella_digital', models.BinaryField(blank=True, db_column='huella_digital', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('tipo_tarea', models.CharField(choices=[('general', 'General'), ('inventario', 'Inventario'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('atencion_cliente', 'Atención Cliente'), ('administrativa', 'Administrativa'), ('urgente', 'Urgente')], db_column='tipo_tarea', default='general', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], db_column='prioridad', default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], db_column='estado', default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='fecha_inicio', null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, db_column='fecha_vencimiento', null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, db_column='fecha_completada', null=True)),
                ('es_recurrente', models.BooleanField(db_column='es_recurrente', default=False)),
                ('frecuencia_recurrencia', models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], db_column='frecuencia_recurrencia', max_length=20, null=True)),
                ('dias_recurrencia', models.JSONField(blank=True, db_column='dias_recurrencia', null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=100, null=True)),
                ('modulo_relacionado', models.CharField(blank=True, db_column='modulo_relacionado', max_length=50, null=True)),
                ('registro_relacionado_id', models.IntegerField(blank=True, db_column='registro_relacionado_id', null=True)),
                ('tiempo_estimado_minutos', models.IntegerField(blank=True, db_column='tiempo_estimado_minutos', null=True)),
                ('tiempo_real_minutos', models.IntegerField(blank=True, db_column='tiempo_real_minutos', null=True)),
                ('porcentaje_completado', models.IntegerField(db_column='porcentaje_completado', default=0)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('archivo_adjunto', models.CharField(blank=True, db_column='archivo_adjunto', max_length=255, null=True)),
                ('requiere_aprobacion', models.BooleanField(db_column='requiere_aprobacion', default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, db_column='fecha_aprobacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('aprobada_por_rut', models.ForeignKey(blank=True, db_column='aprobada_por_rut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_aprobadas', to='empleado.empleado', to_field='rut')),
                ('asignada_a_rut', models.ForeignKey(blank=True, db_column='asignada_a_rut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='empleado.empleado', to_field='rut')),
                ('creada_por_rut', models.ForeignKey(db_column='creada_por_rut', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='empleado.empleado', to_field='rut')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='TareasComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(db_column='comentario')),
                ('archivo_adjunto', models.CharField(blank=True, db_column='archivo_adjunto', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('empleado_rut', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tareas', to='empleado.empleado', to_field='rut')),
                ('tarea_id', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='empleado.tareas')),
            ],
            options={
                'db_table': 'tareas_comentarios',
            },
        ),
        migrations.CreateModel(
            name='TareasHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(db_column='accion', max_length=100)),
                ('campo_modificado', models.CharField(blank=True, db_column='campo_modificado', max_length=50, null=True)),
                ('valor_anterior', models.TextField(blank=True, db_column='valor_anterior', null=True)),
                ('valor_nuevo', models.TextField(blank=True, db_column='valor_nuevo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('empleado_rut', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.CASCADE, related_name='historial_tareas', to='empleado.empleado', to_field='rut')),
                ('tarea_id', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='empleado.tareas')),
            ],
            options={
                'db_table': 'tareas_historial',
            },
        ),
        migrations.CreateModel(
            name='TiposSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('requiere_aprobacion', models.BooleanField(db_column='requiere_aprobacion', default=True)),
                ('dias_anticipacion', models.IntegerField(db_column='dias_anticipacion', default=1)),
                ('color_hex', models.CharField(db_column='color_hex', default='#007bff', max_length=7)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'tipos_solicitudes',
                'indexes': [models.Index(fields=['nombre'], name='tipos_solic_nombre_069cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_rut', models.CharField(blank=True, db_column='empleado_rut', max_length=12, null=True)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
                ('motivo', models.TextField(db_column='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_column='estado', default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, db_column='fecha_aprobacion', null=True)),
                ('comentario_aprobacion', models.TextField(blank=True, db_column='comentario_aprobacion', null=True)),
                ('documento_adjunto', models.CharField(blank=True, db_column='documento_adjunto', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to='empleado.empleado')),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='empleado.empleado')),
                ('tipo_solicitud_id', models.ForeignKey(db_column='tipo_solicitud_id', on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes', to='empleado.tipossolicitudes')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turno', models.CharField(db_column='nombre_turno', max_length=100)),
                ('hora_entrada', models.TimeField(db_column='hora_entrada')),
                ('hora_salida', models.TimeField(db_column='hora_salida')),
                ('tolerancia_minutos', models.IntegerField(db_column='tolerancia_minutos', default=15)),
                ('horas_trabajo', models.DecimalField(db_column='horas_trabajo', decimal_places=2, max_digits=4)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('dias_semana', models.JSONField(blank=True, db_column='dias_semana', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('empleados_rut', models.ForeignKey(db_column='empleados_rut', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleado.empleado', to_field='rut')),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='fecha_fin', null=True)),
                ('dias_semana', models.JSONField(blank=True, db_column='dias_semana', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('empleado_rut', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='empleado.empleado', to_field='rut')),
                ('turno_id', models.ForeignKey(db_column='turno_id', on_delete=django.db.models.deletion.RESTRICT, related_name='horarios_asignados', to='empleado.turno')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='EmpleadosTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='fecha_fin', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('empleados_rut', models.ForeignKey(db_column='empleados_rut', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_turnos', to='empleado.empleado', to_field='rut')),
                ('turno_id', models.ForeignKey(db_column='turno_id', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='empleado.turno')),
            ],
            options={
                'db_table': 'empleados_turnos',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora_entrada', models.DateTimeField(blank=True, db_column='hora_entrada', null=True)),
                ('hora_salida', models.DateTimeField(blank=True, db_column='hora_salida', null=True)),
                ('tipo_entrada', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_entrada', default='biometrico', max_length=20)),
                ('tipo_salida', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_salida', default='biometrico', max_length=20)),
                ('minutos_tarde', models.IntegerField(db_column='minutos_tarde', default=0)),
                ('minutos_extras', models.IntegerField(db_column='minutos_extras', default=0)),
                ('horas_trabajadas', models.DecimalField(blank=True, db_column='horas_trabajadas', decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('permiso', 'Permiso')], db_column='estado', default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('ubicacion_entrada', models.CharField(blank=True, db_column='ubicacion_entrada', max_length=255, null=True)),
                ('ubicacion_salida', models.CharField(blank=True, db_column='ubicacion_salida', max_length=255, null=True)),
                ('ip_entrada', models.CharField(blank=True, db_column='ip_entrada', max_length=45, null=True)),
                ('ip_salida', models.CharField(blank=True, db_column='ip_salida', max_length=45, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, db_column='fecha_validacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('empleado_rut', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleado.empleado', to_field='rut')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_validadas', to='empleado.empleado')),
            ],
            options={
                'db_table': 'asistencias',
                'indexes': [models.Index(fields=['empleado_rut', 'fecha'], name='asistencias_emplead_480d74_idx'), models.Index(fields=['fecha'], name='asistencias_fecha_d405d2_idx'), models.Index(fields=['estado'], name='asistencias_estado_a73000_idx')],
                'unique_together': {('empleado_rut', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('alerta', 'Alerta'), ('urgente', 'Urgente'), ('recordatorio', 'Recordatorio'), ('aprobacion', 'Aprobación')], db_column='tipo', max_length=20)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('mensaje', models.TextField(db_column='mensaje')),
                ('modulo', models.CharField(blank=True, db_column='modulo', max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, db_column='referencia_id', null=True)),
                ('leida', models.BooleanField(db_column='leida', default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, db_column='fecha_lectura', null=True)),
                ('requiere_accion', models.BooleanField(db_column='requiere_accion', default=False)),
                ('url_accion', models.CharField(blank=True, db_column='url_accion', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_expiracion', models.DateTimeField(blank=True, db_column='fecha_expiracion', null=True)),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empleado.empleado')),
            ],
            options={
                'db_table': 'notificaciones',
                'indexes': [models.Index(fields=['empleado_id'], name='notificacio_emplead_187eca_idx'), models.Index(fields=['leida'], name='notificacio_leida_8f2b73_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_f5d897_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_24f290_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['asignada_a_rut'], name='tareas_asignad_48bb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['creada_por_rut'], name='tareas_creada__63d5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['aprobada_por_rut'], name='tareas_aprobad_00d53a_idx'),
        ),
        migrations.AddIndex(
            model_name='tareascomentarios',
            index=models.Index(fields=['tarea_id'], name='tareas_come_tarea_i_b85443_idx'),
        ),
        migrations.AddIndex(
            model_name='tareascomentarios',
            index=models.Index(fields=['empleado_rut'], name='tareas_come_emplead_c81c79_idx'),
        ),
        migrations.AddIndex(
            model_name='tareashistorial',
            index=models.Index(fields=['tarea_id'], name='tareas_hist_tarea_i_f8725d_idx'),
        ),
        migrations.AddIndex(
            model_name='tareashistorial',
            index=models.Index(fields=['empleado_rut'], name='tareas_hist_emplead_88d2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudes',
            index=models.Index(fields=['empleado_id'], name='solicitudes_emplead_1a7743_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudes',
            index=models.Index(fields=['tipo_solicitud_id'], name='solicitudes_tipo_so_acc349_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudes',
            index=models.Index(fields=['estado'], name='solicitudes_estado_9b0551_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudes',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='solicitudes_fecha_i_06b8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empleados_rut'], name='turnos_emplead_376a92_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['nombre_turno'], name='turnos_nombre__960c51_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['activo'], name='turnos_activo_9107c6_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['turno_id'], name='horarios_turno_i_123cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['fecha_inicio'], name='horarios_fecha_i_3f1954_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['empleado_rut'], name='horarios_emplead_326462_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadosturnos',
            index=models.Index(fields=['empleados_rut'], name='empleados_t_emplead_cea80f_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadosturnos',
            index=models.Index(fields=['turno_id'], name='empleados_t_turno_i_d38fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadosturnos',
            index=models.Index(fields=['activo'], name='empleados_t_activo_ce74e3_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadosturnos',
            index=models.Index(fields=['fecha_inicio'], name='empleados_t_fecha_i_a44b05_idx'),
        ),
    ]
