# Generated by Django 5.2.5 on 2025-11-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_column='rut', max_length=12, unique=True)),
                ('nombre', models.CharField(db_column='nombres', max_length=100)),
                ('apellido', models.CharField(db_column='apellidos', max_length=100)),
                ('correo', models.EmailField(blank=True, db_column='email', max_length=100, null=True)),
                ('celular', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('direccion', models.TextField(blank=True, db_column='direccion', null=True)),
                ('cargo', models.CharField(db_column='cargo', max_length=100)),
                ('departamento', models.CharField(blank=True, db_column='departamento', max_length=100, null=True)),
                ('fecha_contratacion', models.DateField(db_column='fecha_contratacion')),
                ('fecha_termino', models.DateField(blank=True, db_column='fecha_termino', null=True)),
                ('salario', models.IntegerField(blank=True, db_column='salario', null=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], db_column='tipo_contrato', default='indefinido', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('desvinculado', 'Desvinculado')], db_column='estado', default='activo', max_length=20)),
                ('password', models.CharField(blank=True, db_column='password', max_length=255, null=True)),
                ('foto_perfil', models.CharField(blank=True, db_column='foto_perfil', max_length=255, null=True)),
                ('huella_digital', models.BinaryField(blank=True, db_column='huella_digital', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora_entrada', models.DateTimeField(blank=True, db_column='hora_entrada', null=True)),
                ('hora_salida', models.DateTimeField(blank=True, db_column='hora_salida', null=True)),
                ('tipo_entrada', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_entrada', default='biometrico', max_length=20)),
                ('tipo_salida', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_salida', default='biometrico', max_length=20)),
                ('minutos_tarde', models.IntegerField(db_column='minutos_tarde', default=0)),
                ('minutos_extras', models.IntegerField(db_column='minutos_extras', default=0)),
                ('horas_trabajadas', models.IntegerField(blank=True, db_column='horas_trabajadas', null=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('permiso', 'Permiso')], db_column='estado', default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('ubicacion_entrada', models.CharField(blank=True, db_column='ubicacion_entrada', max_length=255, null=True)),
                ('ubicacion_salida', models.CharField(blank=True, db_column='ubicacion_salida', max_length=255, null=True)),
                ('ip_entrada', models.CharField(blank=True, db_column='ip_entrada', max_length=45, null=True)),
                ('ip_salida', models.CharField(blank=True, db_column='ip_salida', max_length=45, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, db_column='fecha_validacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('empleado_rut', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleado.empleado', to_field='rut')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_validadas', to='empleado.empleado')),
            ],
            options={
                'db_table': 'asistencias',
                'indexes': [models.Index(fields=['empleado_rut', 'fecha'], name='asistencias_emplead_480d74_idx'), models.Index(fields=['fecha'], name='asistencias_fecha_d405d2_idx'), models.Index(fields=['estado'], name='asistencias_estado_a73000_idx')],
                'unique_together': {('empleado_rut', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turno', models.CharField(db_column='nombre_turno', max_length=100)),
                ('hora_entrada', models.TimeField(db_column='hora_entrada')),
                ('hora_salida', models.TimeField(db_column='hora_salida')),
                ('tolerancia_minutos', models.IntegerField(db_column='tolerancia_minutos', default=15)),
                ('horas_trabajo', models.IntegerField(db_column='horas_trabajo')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('dias_semana', models.JSONField(blank=True, db_column='dias_semana', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('empleados_rut', models.ForeignKey(db_column='empleados_rut', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleado.empleado', to_field='rut')),
            ],
            options={
                'db_table': 'turnos',
                'indexes': [models.Index(fields=['empleados_rut'], name='turnos_emplead_376a92_idx'), models.Index(fields=['nombre_turno'], name='turnos_nombre__960c51_idx'), models.Index(fields=['activo'], name='turnos_activo_9107c6_idx')],
            },
        ),
    ]
