# Generated by Django 5.2.5 on 2025-11-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_rut', models.CharField(db_column='empleado_rut', max_length=12)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora_entrada', models.DateTimeField(blank=True, db_column='hora_entrada', null=True)),
                ('hora_salida', models.DateTimeField(blank=True, db_column='hora_salida', null=True)),
                ('tipo_entrada', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_entrada', default='biometrico', max_length=20)),
                ('tipo_salida', models.CharField(choices=[('biometrico', 'Biométrico'), ('manual', 'Manual'), ('app_movil', 'App Móvil')], db_column='tipo_salida', default='biometrico', max_length=20)),
                ('minutos_tarde', models.IntegerField(db_column='minutos_tarde', default=0)),
                ('minutos_extras', models.IntegerField(db_column='minutos_extras', default=0)),
                ('horas_trabajadas', models.DecimalField(blank=True, db_column='horas_trabajadas', decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('permiso', 'Permiso')], db_column='estado', default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('ubicacion_entrada', models.CharField(blank=True, db_column='ubicacion_entrada', max_length=255, null=True)),
                ('ubicacion_salida', models.CharField(blank=True, db_column='ubicacion_salida', max_length=255, null=True)),
                ('ip_entrada', models.CharField(blank=True, db_column='ip_entrada', max_length=45, null=True)),
                ('ip_salida', models.CharField(blank=True, db_column='ip_salida', max_length=45, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, db_column='fecha_validacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_validadas', to='empleado.empleado')),
            ],
            options={
                'db_table': 'asistencias',
                'indexes': [models.Index(fields=['empleado_rut', 'fecha'], name='asistencias_emplead_480d74_idx'), models.Index(fields=['fecha'], name='asistencias_fecha_d405d2_idx'), models.Index(fields=['estado'], name='asistencias_estado_a73000_idx')],
                'unique_together': {('empleado_rut', 'fecha')},
            },
        ),
    ]
