# Generated by Django 5.2.5 on 2025-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleados_rut', models.CharField(db_column='empleados_rut', max_length=12)),
                ('nombre_turno', models.CharField(db_column='nombre_turno', max_length=100)),
                ('hora_entrada', models.TimeField(db_column='hora_entrada')),
                ('hora_salida', models.TimeField(db_column='hora_salida')),
                ('tolerancia_minutos', models.IntegerField(db_column='tolerancia_minutos', default=15)),
                ('horas_trabajo', models.DecimalField(db_column='horas_trabajo', decimal_places=2, max_digits=4)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('dias_semana', models.JSONField(blank=True, db_column='dias_semana', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'turnos',
                'indexes': [models.Index(fields=['empleados_rut'], name='turnos_emplead_376a92_idx'), models.Index(fields=['nombre_turno'], name='turnos_nombre__960c51_idx'), models.Index(fields=['activo'], name='turnos_activo_9107c6_idx')],
            },
        ),
    ]
