# Generated by Django 5.2.5 on 2025-12-05 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_empleado_apellidos_separados'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        # Eliminar tablas si existen (por si acaso hay tablas parcialmente creadas)
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 1;"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS items_orden_compra;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ordenes_compra;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS proveedores;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 1;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 0;"
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=200, unique=True)),
                ('razon_social', models.CharField(blank=True, db_column='razon_social', max_length=200, null=True)),
                ('rut', models.CharField(blank=True, db_column='rut', max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=20, null=True)),
                ('sitio_web', models.URLField(blank=True, db_column='sitio_web', max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, db_column='direccion', null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, db_column='codigo_postal', max_length=20, null=True)),
                ('pais', models.CharField(db_column='pais', default='Chile', max_length=100)),
                ('contacto_principal', models.CharField(blank=True, db_column='contacto_principal', max_length=200, null=True)),
                ('cargo_contacto', models.CharField(blank=True, db_column='cargo_contacto', max_length=100, null=True)),
                ('email_contacto', models.EmailField(blank=True, db_column='email_contacto', max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, db_column='telefono_contacto', max_length=20, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], db_column='estado', default='activo', max_length=20)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=100, null=True)),
                ('tipo_proveedor', models.CharField(blank=True, db_column='tipo_proveedor', max_length=100, null=True)),
                ('condiciones_pago', models.CharField(blank=True, db_column='condiciones_pago', max_length=100, null=True)),
                ('plazo_entrega', models.CharField(blank=True, db_column='plazo_entrega', max_length=100, null=True)),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=0, max_digits=5)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_actualizados', to='empleado.empleado', db_constraint=False)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to='empleado.empleado', db_constraint=False)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(db_column='numero_orden', max_length=50, unique=True)),
                ('fecha_orden', models.DateField(db_column='fecha_orden')),
                ('fecha_entrega_esperada', models.DateField(blank=True, db_column='fecha_entrega_esperada', null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, db_column='fecha_entrega_real', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('en_transito', 'En Tránsito'), ('recibida', 'Recibida'), ('parcialmente_recibida', 'Parcialmente Recibida'), ('cancelada', 'Cancelada'), ('facturada', 'Facturada')], db_column='estado', default='borrador', max_length=30)),
                ('subtotal', models.IntegerField(db_column='subtotal', default=0)),
                ('descuento', models.IntegerField(db_column='descuento', default=0)),
                ('impuestos', models.IntegerField(db_column='impuestos', default=0)),
                ('total', models.IntegerField(db_column='total', default=0)),
                ('moneda', models.CharField(db_column='moneda', default='CLP', max_length=10)),
                ('condiciones_pago', models.CharField(blank=True, db_column='condiciones_pago', max_length=200, null=True)),
                ('metodo_envio', models.CharField(blank=True, db_column='metodo_envio', max_length=100, null=True)),
                ('direccion_entrega', models.TextField(blank=True, db_column='direccion_entrega', null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('numero_factura', models.CharField(blank=True, db_column='numero_factura', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, db_column='fecha_aprobacion', null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_aprobadas', to='empleado.empleado', db_constraint=False)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to='empleado.empleado', db_constraint=False)),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='proveedores.proveedor', db_constraint=False)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, db_column='codigo_producto', max_length=50, null=True)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('cantidad_recibida', models.IntegerField(db_column='cantidad_recibida', default=0)),
                ('unidad_medida', models.CharField(db_column='unidad_medida', default='unidad', max_length=20)),
                ('precio_unitario', models.IntegerField(db_column='precio_unitario')),
                ('descuento', models.IntegerField(db_column='descuento', default=0)),
                ('precio_total', models.IntegerField(db_column='precio_total')),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='inventario.inventario', db_constraint=False)),
                ('orden_compra', models.ForeignKey(db_column='orden_compra_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proveedores.ordencompra', db_constraint=False)),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Órdenes de Compra',
                'db_table': 'items_orden_compra',
                'indexes': [models.Index(fields=['orden_compra'], name='items_orden_orden_c_f25b04_idx'), models.Index(fields=['producto'], name='items_orden_product_bb8921_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='proveedores_nombre_4e7949_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='proveedores_estado_e45323_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo'], name='proveedores_activo_068092_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['numero_orden'], name='ordenes_com_numero__72b9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor'], name='ordenes_com_proveed_6d9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado'], name='ordenes_com_estado_8ac831_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='ordenes_com_fecha_o_6951ee_idx'),
        ),
    ]
